import { NQueens, NQueensVisualized } from "problems/n-queens";

test<NQueens<8, 8>>(); // $ExpectType [[3, 7], [1, 6], [6, 5], [2, 4], [5, 3], [7, 2], [4, 1], [0, 0]]
test<NQueens<4, 4>>(); // $ExpectType [[2, 3], [0, 2], [3, 1], [1, 0]]
test<NQueens<4, 3>>(); // $ExpectType undefined

// tslint:disable-next-line: max-line-length no-irregular-whitespace
// $ExpectType "                                                                                                                                                                                                         ♕ ◼️ ◻️ ◼️ ◻️ ◼️ ◻️ ◼️                                                                                                                                                                                                          ◼️ ◻️ ◼️ ◻️ ♕ ◻️ ◼️ ◻️                                                                                                                                                                                                          ◻️ ◼️ ◻️ ◼️ ◻️ ◼️ ◻️ ♕                                                                                                                                                                                                          ◼️ ◻️ ◼️ ◻️ ◼️ ♕ ◼️ ◻️                                                                                                                                                                                                          ◻️ ◼️ ♕ ◼️ ◻️ ◼️ ◻️ ◼️                                                                                                                                                                                                          ◼️ ◻️ ◼️ ◻️ ◼️ ◻️ ♕ ◻️                                                                                                                                                                                                          ◻️ ♕ ◻️ ◼️ ◻️ ◼️ ◻️ ◼️                                                                                                                                                                                                          ◼️ ◻️ ◼️ ♕ ◼️ ◻️ ◼️ ◻️                                                                                                                                                                                                          "
test<NQueensVisualized<NQueens<8, 8>, 8>>();
