name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  node_version: 16

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      release_required: ${{ steps.release_required.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
          registry-url: "https://registry.npmjs.org"
          scope: "@jakzo"
      - run: git config --global user.name "github-actions[bot]" &&
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: yarn install --frozen-lockfile
      # - run: yarn util:generate-docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
      - run: yarn publish --patch --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --no-verify
      - id: version
        run: echo "::set-output name=version::$(yarn --silent util:print-version)"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
